### PR TITLE
Rework docker setup to use security best practices

### PR DESCRIPTION
**Pull request by ChristophNiehoff**
In this PR the existing docker file is refactored to a docker-compose setup.
Following docker best practices, the application is split up into two different containers:

1. nginx reverse proxy serving the client app
2. nodejs container serving the game server backend

Alpine-based base images are used. Security best practices are used as advised [this this snyk blog post](https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/).

NOTE: This PR contains a major rework of the source code's folder structure. The reason is to have a clearer separation of client and server code. This increases the readability of the code and allows to separate the code onto the containers in a more transparent way.

### CODE REVIEW

**Comment by ChristophNiehoff** [comment]
@dehydr8 I believe this PR would break the heroku setup. What do you think? Do you know, whether the heroku app is still actively used?

**Comment by dehydr8** [comment]
@ChristophNiehoff the build process currently pushes the image to dockerhub (okhalid/eop) and the heroku app registry. After a successful build when a tag is created, it runs the release step on heroku with that docker image.

A demo application on heroku would be nice to let people play around and experience the game. I'm not sure whether we can use the compose file directly on heroku, maybe we can have a separate Dockerfile for the single image setup and build that in our CI stage.

What do you think?

**Comment by ChristophNiehoff** [comment]
@dehydr8 Yes, I agree. It's good to have something the users can play with. I will add a separate Dockerfile for heroku.

**Comment by ChristophNiehoff** [comment]
@dehydr8 I re-added a dockerfile for a single-container deployment. Could you check whether this fixes the heroku deployment?

**Comment by ChristophNiehoff** [comment]
Works like charm. Thanks!  Merging this to master...

**Pull request merged**
