### PR TITLE
Updated Dependencies

### PR DESCRIPTION
**Pull request by matthewejones**
Updated most* packages to latest versions (resolves issue #77 )

Reactstrap only supports bootstrap 4 so bootstrap cannot be updated.

The newest version of `react-scripts` will crash as it tries to resolve urls in the css files. The new update relies on a different version of `css-loader` in its newest version. [This link](https://github.com/facebook/create-react-app/issues/9870) is to an issue in `react-scripts` which has many people posting workarounds. [This link](https://github.com/webpack-contrib/css-loader/issues/1136) is to `css-loader` where the person explains why he's changed this functionality.

Either way I think for now the current version of react-scripts is fine

*This also includes yesterday's newest update for boardgame.io (0.45.2 => 0.46.1). I didn't want to put it in the other pull request because everything was reviewed and tested. I had a small problem with the update when I first installed it. It couldn't import one of the files. This was resolved by removing my node-modules folder and then installing it again. I then couldn't replicate the issue so I'm assuming it was just a problem with my node installation.

After all these updates (including boardgame.io) there are now 6 vulnerabilities (5 moderate, 1 high) instead of 45994 vulnerabilities (42372 low, 223 moderate, 3395 high, 4 critical)

### CODE REVIEW

**Comment by matthewejones** [comment]
I've just had a look at pr #51 and there was an issue with deployment.

I'm not really sure how to test this to see if the issue is still there.

**Comment by ChristophNiehoff** [comment]
@matthewejones I am sorry. As far as I remember #51 wasn't a problem with deployment, but rather a runtime error (and no build time error). I believe, you can reproduce the issue by just starting the game locally. If that doesn't work you can create a branch and  I can deploy it to our staging environment.

**Comment by ChristophNiehoff** [comment]
@matthewejones Di I unserstand it correctly that the remaining high vulnerability only comes from react-scripts?

**Comment by matthewejones** [comment]
> @matthewejones Do I understand correctly that the remaining high vulnerability only comes from react-scripts?

Yeah, the remaining vulnerabilities are all from react-scripts

This is the high one:

```
  High            Prototype Pollution

  Package         immer

  Dependency of   react-scripts

  Path            react-scripts > react-dev-utils > immer

  More info       https://npmjs.com/advisories/1603
```

**Comment by matthewejones** [comment]
> @matthewejones I am sorry. As far as I remember #51 wasn't a problem with deployment, but rather a runtime error (and no build time error). I believe, you can reproduce the issue by just starting the game locally. If that doesn't work you can create a branch and I can deploy it to our staging environment.

Ok, I was having an issue with importing, I think this is the same issue. This is what I was getting in the tests:
```

    TypeError: Cannot read property 'V' of undefined

       5 | joint.shapes.tm = {};
       6 |
    >  7 | joint.shapes.tm.Highlighter = {
         |                        ^
       8 |     highlighter: {
       9 |         name: 'addClass',
      10 |         options: {

      at Object.<anonymous> (src/client/jointjs/shapes.js:7:24)
      at Object.<anonymous> (src/client/components/model/model.js:22:38)
      at Object.<anonymous> (src/client/components/board/board.js:3:1)
      at Object.<anonymous> (src/client/components/board/board.test.js:3:1)
```

When running the game locally:
image


What you were getting a few months ago:
```
Uncaught TypeError: function call() { [native code] } is not a function
    at joint.min.js:448
    at ae (joint.min.js:447)
    at ue (joint.min.js:479)
    at joint.min.js:481
    at Object.<anonymous> (joint.min.js:9)
    at Object.<anonymous> (joint.min.js:17507)
    at f ((index):1)
    at Object.<anonymous> (index.js:3)
    at f ((index):1)
    at Module.213 (shapes.js:377)
```

**Pull request merged**
