### PR TITLE
fix threatbar hidden behind status bar

### PR DESCRIPTION
**Pull request by matthewejones**
When the threatbar has many threats in it, it is hidden behind the status bar an cannot be accessed.

This was to allow the cards in the status bar to be clickable.

I think a better way to resolve this is to have the threatbar in front of the status bar but only the visible part stops the cards being clicked. The threatbar can then be closed to allow the cards behind to be clicked.

### CODE REVIEW

**Comment by matthewejones** [comment]
Before, threat is blocked off:

image

**Comment by ChristophNiehoff** [comment]
@matthewejones Does this mean that there will be a scrollbar with many threats?

**Comment by matthewejones** [comment]
Yeah, this is the new behaviour: cards which aren't covered by the threatbar can still be clicked
image

with more threats there's a scroll bar, the cards behind here can't be clicked when the threatbar is open but it can easily be closed by clicking off it
image

**Comment by matthewejones** [comment]
If you don't want it covering the cards, I can make it shorter so it just comes up to the status bar.

**Comment by ChristophNiehoff** [comment]
Added a small commit that dynamically computes the max-height of the threat bar, such that it does not stretch over the cards.

**Pull request merged**
